[project]
# اترك هذا القسم كما هو أو فارغاً إذا كنت تستخدم .env للمفاتيح

[UI]
# إخفاء شاشة الترحيب/الـ README الافتراضية
show_readme_as_default = false

# الاسم الذي سيظهر في أعلى الواجهة
name = "مساعد تربية نينوى وجامعة الموصل"
